import "server-only";
import type {
  GraphData,
  Cell,
  Disease,
  Regimen,
  Drug,
  EntityKind,
} from "./types";

/**
 * Server-side data access. Reads the full graph and performs per-entity CRUD.
 *
 * When `DATABASE_URL` is set it talks to Neon via Drizzle. When it is NOT set
 * (e.g. a fresh clone before provisioning a DB), it falls back to the checked-
 * in seed fixture so the viewer is runnable immediately. Writes require a real
 * DB and throw a clear error in fallback mode.
 */

export function hasDatabase(): boolean {
  return Boolean(process.env.DATABASE_URL);
}

/** Read the entire graph, assembling ID-array edges from the join tables. */
export async function readGraphData(): Promise<GraphData> {
  if (!hasDatabase()) {
    const seed = (await import("@/db/seed-data.json")).default;
    return seed as GraphData;
  }

  const { db, schema } = await import("@/db");
  const [cells, diseases, regimens, drugs, dc, rd, dr] = await Promise.all([
    db.select().from(schema.cells),
    db.select().from(schema.diseases),
    db.select().from(schema.regimens),
    db.select().from(schema.drugs),
    db.select().from(schema.diseaseCells),
    db.select().from(schema.regimenDiseases),
    db.select().from(schema.drugRegimens),
  ]);

  const cellIdsByDisease = groupBy(dc, (r) => r.diseaseId, (r) => r.cellId);
  const diseaseIdsByRegimen = groupBy(rd, (r) => r.regimenId, (r) => r.diseaseId);
  const regimenIdsByDrug = groupBy(dr, (r) => r.drugId, (r) => r.regimenId);

  return {
    cells: cells.map(
      (c): Cell => ({
        id: c.id,
        name: c.name,
        parentId: c.parentId,
        lineage: c.lineage,
        order: c.order,
      }),
    ),
    diseases: diseases.map(
      (d): Disease => ({
        id: d.id,
        name: d.name,
        abbreviation: d.abbreviation,
        cellIds: cellIdsByDisease.get(d.id) ?? [],
      }),
    ),
    regimens: regimens.map(
      (r): Regimen => ({
        id: r.id,
        name: r.name,
        diseaseIds: diseaseIdsByRegimen.get(r.id) ?? [],
      }),
    ),
    drugs: drugs.map(
      (d): Drug => ({
        id: d.id,
        name: d.name,
        mechanism: d.mechanism,
        toxicities: d.toxicities,
        regimenIds: regimenIdsByDrug.get(d.id) ?? [],
      }),
    ),
  };
}

function groupBy<T, K, V>(
  rows: T[],
  keyFn: (row: T) => K,
  valFn: (row: T) => V,
): Map<K, V[]> {
  const map = new Map<K, V[]>();
  for (const row of rows) {
    const k = keyFn(row);
    const list = map.get(k);
    if (list) list.push(valFn(row));
    else map.set(k, [valFn(row)]);
  }
  return map;
}

/** Guard used by write paths: throws when no DB is configured. */
export function assertWritable() {
  if (!hasDatabase()) {
    throw new Error(
      "No DATABASE_URL configured. Editing requires a Neon database — see .env.example.",
    );
  }
}

// --------------------------------------------------------------------------
// Writes. All go through Drizzle; each replaces the entity row and its
// owned join-table edges. The neon-http driver batches these atomically via
// db.transaction().
// --------------------------------------------------------------------------

import { eq } from "drizzle-orm";
import type { InputByKind } from "./types";

/** Create a cell. `id` is generated by the caller (route handler). */
export async function createCell(id: string, input: InputByKind["cell"]) {
  assertWritable();
  const { db, schema } = await import("@/db");
  await db.insert(schema.cells).values({
    id,
    name: input.name,
    parentId: input.parentId,
    lineage: input.lineage,
    order: input.order,
  });
}

export async function updateCell(id: string, input: InputByKind["cell"]) {
  assertWritable();
  const { db, schema } = await import("@/db");
  await db
    .update(schema.cells)
    .set({
      name: input.name,
      parentId: input.parentId,
      lineage: input.lineage,
      order: input.order,
    })
    .where(eq(schema.cells.id, id));
}

export async function createDisease(id: string, input: InputByKind["disease"]) {
  assertWritable();
  const { db, schema } = await import("@/db");
  await db.transaction(async (tx) => {
    await tx
      .insert(schema.diseases)
      .values({ id, name: input.name, abbreviation: input.abbreviation });
    if (input.cellIds.length) {
      await tx
        .insert(schema.diseaseCells)
        .values(input.cellIds.map((cellId) => ({ diseaseId: id, cellId })));
    }
  });
}

export async function updateDisease(id: string, input: InputByKind["disease"]) {
  assertWritable();
  const { db, schema } = await import("@/db");
  await db.transaction(async (tx) => {
    await tx
      .update(schema.diseases)
      .set({ name: input.name, abbreviation: input.abbreviation })
      .where(eq(schema.diseases.id, id));
    await tx.delete(schema.diseaseCells).where(eq(schema.diseaseCells.diseaseId, id));
    if (input.cellIds.length) {
      await tx
        .insert(schema.diseaseCells)
        .values(input.cellIds.map((cellId) => ({ diseaseId: id, cellId })));
    }
  });
}

export async function createRegimen(id: string, input: InputByKind["regimen"]) {
  assertWritable();
  const { db, schema } = await import("@/db");
  await db.transaction(async (tx) => {
    await tx.insert(schema.regimens).values({ id, name: input.name });
    if (input.diseaseIds.length) {
      await tx
        .insert(schema.regimenDiseases)
        .values(input.diseaseIds.map((diseaseId) => ({ regimenId: id, diseaseId })));
    }
  });
}

export async function updateRegimen(id: string, input: InputByKind["regimen"]) {
  assertWritable();
  const { db, schema } = await import("@/db");
  await db.transaction(async (tx) => {
    await tx
      .update(schema.regimens)
      .set({ name: input.name })
      .where(eq(schema.regimens.id, id));
    await tx
      .delete(schema.regimenDiseases)
      .where(eq(schema.regimenDiseases.regimenId, id));
    if (input.diseaseIds.length) {
      await tx
        .insert(schema.regimenDiseases)
        .values(input.diseaseIds.map((diseaseId) => ({ regimenId: id, diseaseId })));
    }
  });
}

export async function createDrug(id: string, input: InputByKind["drug"]) {
  assertWritable();
  const { db, schema } = await import("@/db");
  await db.transaction(async (tx) => {
    await tx.insert(schema.drugs).values({
      id,
      name: input.name,
      mechanism: input.mechanism,
      toxicities: input.toxicities,
    });
    if (input.regimenIds.length) {
      await tx
        .insert(schema.drugRegimens)
        .values(input.regimenIds.map((regimenId) => ({ drugId: id, regimenId })));
    }
  });
}

export async function updateDrug(id: string, input: InputByKind["drug"]) {
  assertWritable();
  const { db, schema } = await import("@/db");
  await db.transaction(async (tx) => {
    await tx
      .update(schema.drugs)
      .set({
        name: input.name,
        mechanism: input.mechanism,
        toxicities: input.toxicities,
      })
      .where(eq(schema.drugs.id, id));
    await tx.delete(schema.drugRegimens).where(eq(schema.drugRegimens.drugId, id));
    if (input.regimenIds.length) {
      await tx
        .insert(schema.drugRegimens)
        .values(input.regimenIds.map((regimenId) => ({ drugId: id, regimenId })));
    }
  });
}

/**
 * Delete an entity by kind + id. Join-table edges cascade automatically via
 * the FK constraints; deleting a cell nulls its children's parentId (also via
 * the FK `on delete set null`).
 */
export async function deleteEntity(kind: EntityKind, id: string) {
  assertWritable();
  const { db, schema } = await import("@/db");
  const table = {
    cell: schema.cells,
    disease: schema.diseases,
    regimen: schema.regimens,
    drug: schema.drugs,
  }[kind];
  await db.delete(table).where(eq(table.id, id));
}

/** All existing IDs for a kind (used to generate collision-free new IDs). */
export async function existingIds(kind: EntityKind): Promise<string[]> {
  const { db, schema } = await import("@/db");
  const table = {
    cell: schema.cells,
    disease: schema.diseases,
    regimen: schema.regimens,
    drug: schema.drugs,
  }[kind];
  const rows = await db.select({ id: table.id }).from(table);
  return rows.map((r) => r.id);
}

export type { EntityKind };
